### ISSUE TITLE
Simulation scripts and result visualization

### ISSUE THREAD

**Issue by kunzi051** [sisl/SceneInformer#8]
Hi, great work!
I've visualize scenarios and train a model by using a very small dataset. I got like "/SceneInformer-main/outputs/2025-02-21T07-51-20_scene_informer/checkpoints/interval-epoch=000779-step=000060000.ckpt". 

1. I wonder why I got three checkpoints? 
- outputs/2025-02-21T07-51-20_scene_informer
    - checkpoints
        - interval-epoch=000779-step=000060000.ckpt
        - interval-epoch=000519-step=000040000.ckpt
        - interval-epoch=000259-step=000020000.ckpt
    - configs
        - 2025-02-21T07-51-20-project.yaml
        - 2025-02-21T07-51-20-lightning.yaml
2. I wanna set max epochs. However, I set in scene_infomer.yaml but it didn't work.
```
lightning:
  trainer:
    max_epochs: 100
    benchmark: true
    accumulate_grad_batches: 2
    precision: 16-mixed
    gradient_clip_norm: 1.0
    val_check_interval: 10 # 10000
    limit_val_batches: 0.1
    devices: [0]
    accelerator: "cuda"
```
3. What should I do after training a model? How can I simulate a scenario, visual occulusion occupancy probabilities and future trajectories like Fig.1,4,5 and Table 1?
